# Generated by Django 4.2.11 on 2024-03-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorADC', '0001_initial'),
    ]

    operations = [
    ]
