# Generated by Django 4.2.11 on 2024-04-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorADC', '0002_auto_20240329_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=240, verbose_name='Date')),
                ('tournament', models.CharField(max_length=240, verbose_name='Tournament')),
                ('matchId', models.CharField(max_length=240, verbose_name='MatchId')),
                ('seriesId', models.IntegerField(verbose_name='SeriesId')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('summonnerName', models.CharField(max_length=240, verbose_name='SummonnerName')),
                ('xpd15', models.IntegerField(verbose_name='XPD@15')),
                ('gd15', models.IntegerField(verbose_name='GD@15')),
                ('csMin', models.FloatField(verbose_name='CS/Min')),
                ('kills', models.IntegerField(verbose_name='Kills')),
                ('deaths', models.IntegerField(verbose_name='Deaths')),
                ('assists', models.IntegerField(verbose_name='Assists')),
                ('kp', models.FloatField(verbose_name='KP%')),
                ('wardPlaced', models.IntegerField(verbose_name='WardPlaced')),
                ('dpm', models.FloatField(verbose_name='Damage/Min')),
                ('totalDamageDealtToBuilding', models.FloatField(verbose_name='TotalDamageDealtToBuilding')),
                ('totalDamageDealtToObjectives', models.FloatField(verbose_name='TotalDamageDealtToObjectives')),
                ('jungleProximity', models.FloatField(verbose_name='JungleProximity')),
                ('topLanePresence', models.FloatField(verbose_name='TopLanePresence')),
                ('jungleAllyTopPresence', models.FloatField(verbose_name='jungleAllyTopPresence')),
                ('jungleEnemyTopPresence', models.FloatField(verbose_name='JungleEnemyTopPresence')),
                ('riverTopPresence', models.FloatField(verbose_name='riverTopPresence')),
            ],
        ),
    ]
