# Generated by Django 4.2.11 on 2024-04-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorADC', '0004_behaviorTop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorJungle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=240, verbose_name='Date')),
                ('tournament', models.CharField(max_length=240, verbose_name='Tournament')),
                ('matchId', models.CharField(max_length=240, verbose_name='MatchId')),
                ('seriesId', models.IntegerField(verbose_name='SeriesId')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('summonnerName', models.CharField(max_length=240, verbose_name='SummonnerName')),
                ('xpd15', models.IntegerField(verbose_name='XPD@15')),
                ('gd15', models.IntegerField(verbose_name='GD@15')),
                ('kills', models.IntegerField(verbose_name='Kills')),
                ('deaths', models.IntegerField(verbose_name='Deaths')),
                ('assists', models.IntegerField(verbose_name='Assists')),
                ('kp', models.FloatField(verbose_name='KP%')),
                ('dpm', models.FloatField(verbose_name='Damage/Min')),
                ('topLanePresence', models.FloatField(verbose_name='topLanePresence')),
                ('midLanePresence', models.FloatField(verbose_name='midLanePresence')),
                ('botLanePresence', models.FloatField(verbose_name='botLanePresence')),
                ('jungleAllyTopPresence', models.FloatField(verbose_name='jungleAllyTopPresence')),
                ('jungleAllyBotPresence', models.FloatField(verbose_name='jungleAllyBotPresence')),
                ('jungleEnemyTopPresence', models.FloatField(verbose_name='jungleEnemyTopPresence')),
                ('jungleEnemyBotPresence', models.FloatField(verbose_name='jungleEnemyBotPresence')),
                ('riverBotPresence', models.FloatField(verbose_name='riverBotPresence')),
                ('riverTopPresence', models.FloatField(verbose_name='riverTopPresence')),
            ],
        ),
    ]
