# Generated by Django 4.2.11 on 2024-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorADC', '0007_behaviorsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioradc',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behaviorjungle',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behaviormid',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behaviorsupport',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behaviortop',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
    ]
