# Generated by Django 4.2.11 on 2024-05-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorADC', '0008_behavioradc_gamenumber_behaviorjungle_gamenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioradc',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='behaviorjungle',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='behaviormid',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='behaviorsupport',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='behaviortop',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
