# Generated by Django 4.2.11 on 2024-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorModelsMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='uuid')),
                ('modelType', models.CharField(max_length=240, verbose_name='model_type')),
                ('modelName', models.CharField(max_length=240, verbose_name='model_name')),
                ('role', models.CharField(max_length=240, verbose_name='role')),
                ('kmo', models.FloatField(verbose_name='kmo')),
                ('tournamentDict', models.CharField(max_length=1000, verbose_name='tournament_dict')),
            ],
        ),
    ]
