# Generated by Django 4.2.11 on 2024-05-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviormodelsmetadata',
            name='factorsName',
            field=models.CharField(default='a', max_length=1000, verbose_name='factorsName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behaviormodelsmetadata',
            name='nbFactors',
            field=models.IntegerField(default=1, verbose_name='nbFactors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='behaviormodelsmetadata',
            name='selected',
            field=models.BooleanField(default=1, verbose_name='selected'),
            preserve_default=False,
        ),
    ]
