# Generated by Django 4.2.11 on 2024-04-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=240, verbose_name='Date')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('seriesId', models.IntegerField(verbose_name='Seriesid')),
                ('teamBlue', models.CharField(max_length=240, verbose_name='teamBlue')),
                ('teamRed', models.CharField(max_length=240, verbose_name='teamRed')),
                ('winningTeam', models.IntegerField(verbose_name='winningTeam')),
            ],
        ),
    ]
