# Generated by Django 4.2.11 on 2024-04-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0001_initial'),
    ]

    operations = [
    ]
