# Generated by Django 4.2.11 on 2024-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0002_GameMetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemetadata',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='gameNumber'),
            preserve_default=False,
        ),
    ]
