# Generated by Django 4.2.11 on 2024-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0003_gamemetadata_gamenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemetadata',
            name='tournament',
            field=models.CharField(default='a', max_length=240, verbose_name='Tournament'),
            preserve_default=False,
        ),
    ]
