# Generated by Django 4.2.11 on 2024-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0004_gamemetadata_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemetadata',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
