# Generated by Django 5.0.6 on 2024-12-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0005_alter_gamemetadata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemetadata',
            name='dragonBlueKills',
            field=models.IntegerField(default=1, verbose_name='dragonBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='dragonRedKills',
            field=models.IntegerField(default=1, verbose_name='dragonRedKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='krubsBlueKills',
            field=models.IntegerField(default=1, verbose_name='krubsBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='krubsRedKills',
            field=models.IntegerField(default=1, verbose_name='krubsRedKills'),
            preserve_default=False,
        ),
    ]
