# Generated by Django 5.0.6 on 2024-12-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0006_gamemetadata_dragonbluekills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemetadata',
            name='krubsBlueKills',
        ),
        migrations.RemoveField(
            model_name='gamemetadata',
            name='krubsRedKills',
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='baronBlueKills',
            field=models.IntegerField(default=0, verbose_name='baronBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='baronRedKills',
            field=models.IntegerField(default=0, verbose_name='baronRedKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='elderBlueKills',
            field=models.IntegerField(default=0, verbose_name='elderBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='elderRedKills',
            field=models.IntegerField(default=0, verbose_name='elderRedKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='firstBlood',
            field=models.IntegerField(default=0, verbose_name='firstBlood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='firstTower',
            field=models.IntegerField(default=0, verbose_name='firstTower'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='heraldBlueKills',
            field=models.IntegerField(default=0, verbose_name='heraldBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='heraldRedKills',
            field=models.IntegerField(default=0, verbose_name='heraldRedKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='turretBlueKills',
            field=models.IntegerField(default=0, verbose_name='turretBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='turretRedKills',
            field=models.IntegerField(default=0, verbose_name='turretRedKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='voidGrubsBlueKills',
            field=models.IntegerField(default=0, verbose_name='voidGrubsBlueKills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemetadata',
            name='voidGrubsRedKills',
            field=models.IntegerField(default=0, verbose_name='voidGrubsRedKills'),
            preserve_default=False,
        ),
    ]
