# Generated by Django 5.0.6 on 2024-12-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0007_remove_gamemetadata_krubsbluekills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemetadata',
            name='elderBlueKills',
        ),
        migrations.RemoveField(
            model_name='gamemetadata',
            name='elderRedKills',
        ),
    ]
