# Generated by Django 5.0.6 on 2024-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0008_remove_gamemetadata_elderbluekills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemetadata',
            name='gameDuration',
            field=models.IntegerField(default=1, verbose_name='gameDuration'),
            preserve_default=False,
        ),
    ]
