import pandas as pd
from Draft.models import DraftPickOrder
from tqdm import tqdm

def refresh_draftPickOrder():
    csv_draft_pick_order : str = "./databases/drafts/draft_pick_order.csv"

    df_draft_pick_order : pd.DataFrame = pd.read_csv(csv_draft_pick_order, sep=";", dtype={
        "Date": 'string',
        "Tournament": 'string',
        "Patch": 'string',
        "SeriesId": 'int64',
        "Winner": 'int64',
        "GameNumber": 'int64',
        "teamBlue": 'string',
        "teamRed": 'string',
        "BB1": 'string',
        "BB2": 'string',
        "BB3": 'string',
        "BB4": 'string',
        "BB5": 'string',
        "BP1": 'string',
        "BP2": 'string',
        "BP3": 'string',
        "BP4": 'string',
        "BP5": 'string',
        "RB1": 'string',
        "RB2": 'string',
        "RB3": 'string',
        "RB4": 'string',
        "RB5": 'string',
        "RP1": 'string',
        "RP2": 'string',
        "RP3": 'string',
        "RP4": 'string',
        "RP5": 'string',
    })
    for _, row in tqdm(df_draft_pick_order.iterrows(), total=df_draft_pick_order.shape[0]):
        draftPickOrder = DraftPickOrder(
            date = row["Date"],
            tournament = row["Tournament"],
            patch = row["Patch"],
            seriesId = row["SeriesId"],
            winner = row["Winner"],
            gameNumner = row["GameNumber"],
            teamBlue = row["teamBlue"],
            teamRed = row["teamRed"],
            bb1 = row["BB1"],
            bb2 = row["BB2"],
            bb3 = row["BB3"],
            bb4 = row["BB4"],
            bb5 = row["BB5"],
            bp1 = row["BP1"],
            bp2 = row["BP2"],
            bp3 = row["BP3"],
            bp4 = row["BP4"],
            bp5 = row["BP5"],
            rb1 = row["RB1"],
            rb2 = row["RB2"],
            rb3 = row["RB3"],
            rb4 = row["RB4"],
            rb5 = row["RB5"],
            rp1 = row["RP1"],
            rp2 = row["RP2"],
            rp3 = row["RP3"],
            rp4 = row["RP4"],
            rp5 = row["RP5"]
        )
        if not(DraftPickOrder.objects.filter(
            date = row["Date"],
            tournament = row["Tournament"],
            patch = row["Patch"],
            seriesId = row["SeriesId"],
            winner = row["Winner"],
            gameNumner = row["GameNumber"],
            teamBlue = row["teamBlue"],
            teamRed = row["teamRed"],
            bb1 = row["BB1"],
            bb2 = row["BB2"],
            bb3 = row["BB3"],
            bb4 = row["BB4"],
            bb5 = row["BB5"],
            bp1 = row["BP1"],
            bp2 = row["BP2"],
            bp3 = row["BP3"],
            bp4 = row["BP4"],
            bp5 = row["BP5"],
            rb1 = row["RB1"],
            rb2 = row["RB2"],
            rb3 = row["RB3"],
            rb4 = row["RB4"],
            rb5 = row["RB5"],
            rp1 = row["RP1"],
            rp2 = row["RP2"],
            rp3 = row["RP3"],
            rp4 = row["RP4"],
            rp5 = row["RP5"]).count() > 0):
            
            draftPickOrder.save()