# Generated by Django 4.2.11 on 2024-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=240, verbose_name='Date')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('seriesId', models.IntegerField(verbose_name='SeriesId')),
                ('winner', models.IntegerField(verbose_name='Winner')),
                ('bb1', models.CharField(max_length=240, verbose_name='BB1')),
                ('bb2', models.CharField(max_length=240, verbose_name='BB2')),
                ('bb3', models.CharField(max_length=240, verbose_name='BB3')),
                ('bb4', models.CharField(max_length=240, verbose_name='BB4')),
                ('bb5', models.CharField(max_length=240, verbose_name='BB5')),
                ('bp1', models.CharField(max_length=240, verbose_name='BP1')),
                ('bp2', models.CharField(max_length=240, verbose_name='BP3')),
                ('bp3', models.CharField(max_length=240, verbose_name='BP3')),
                ('bp4', models.CharField(max_length=240, verbose_name='BP4')),
                ('bp5', models.CharField(max_length=240, verbose_name='BP5')),
                ('rb1', models.CharField(max_length=240, verbose_name='RB1')),
                ('rb2', models.CharField(max_length=240, verbose_name='RB3')),
                ('rb3', models.CharField(max_length=240, verbose_name='RB3')),
                ('rb4', models.CharField(max_length=240, verbose_name='RB4')),
                ('rb5', models.CharField(max_length=240, verbose_name='RB5')),
                ('rp1', models.CharField(max_length=240, verbose_name='RP1')),
                ('rp2', models.CharField(max_length=240, verbose_name='RP3')),
                ('rp3', models.CharField(max_length=240, verbose_name='RP3')),
                ('rp4', models.CharField(max_length=240, verbose_name='RP4')),
                ('rp5', models.CharField(max_length=240, verbose_name='RP5')),
            ],
        ),
    ]
