# Generated by Django 4.2.11 on 2024-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0003_draftpickorder_tournament_draftplayerpick_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpickorder',
            name='gameNumner',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftplayerpick',
            name='gameNumber',
            field=models.IntegerField(default=1, verbose_name='GameNumber'),
            preserve_default=False,
        ),
    ]
