# Generated by Django 4.2.11 on 2024-04-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0004_draftpickorder_gamenumner_draftplayerpick_gamenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpickorder',
            name='teamBlue',
            field=models.CharField(default='a', max_length=240, verbose_name='teamBlue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftpickorder',
            name='teamRed',
            field=models.CharField(default='a', max_length=240, verbose_name='teamRed'),
            preserve_default=False,
        ),
    ]
