# Generated by Django 4.2.11 on 2024-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0005_draftpickorder_teamblue_draftpickorder_teamred'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionDraftStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(max_length=240, verbose_name='ChampionName')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('tournament', models.CharField(max_length=240, verbose_name='Tournament')),
                ('side', models.CharField(max_length=240, verbose_name='Side')),
                ('winRate', models.FloatField(verbose_name='WinRate')),
                ('globalPickRate', models.FloatField(verbose_name='GlobalPickRate')),
                ('pickRate1Rota', models.FloatField(verbose_name='PickRate1Rota')),
                ('pickRate2Rota', models.FloatField(verbose_name='PickRate2Rota')),
                ('globalBanRate', models.FloatField(verbose_name='GlobalBanRate')),
                ('banRate1Rota', models.FloatField(verbose_name='BanRate1Rota')),
                ('banRate2Rota', models.FloatField(verbose_name='BanRate2Rota')),
                ('mostPopularPickOrder', models.IntegerField(verbose_name='MostPopularPickOrder')),
                ('blindPick', models.FloatField(verbose_name='BlindPick')),
            ],
        ),
    ]
