# Generated by Django 4.2.11 on 2024-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0007_championdraftstats_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championdraftstats',
            name='role',
        ),
    ]
