# Generated by Django 4.2.11 on 2024-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0008_remove_championdraftstats_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='championdraftstats',
            name='mostPopularRole',
            field=models.CharField(default='Top', max_length=240, verbose_name='MostPopularRole'),
            preserve_default=False,
        ),
    ]
