# Generated by Django 4.2.11 on 2024-05-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0009_championdraftstats_mostpopularrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonnerName', models.CharField(max_length=240, verbose_name='SummonnerName')),
                ('championName', models.CharField(max_length=240, verbose_name='ChampionName')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('tournament', models.CharField(max_length=240, verbose_name='Tournament')),
                ('globalPickRate', models.FloatField(verbose_name='GlobalPickRate')),
                ('winRate', models.FloatField(verbose_name='WinRate')),
                ('nbGames', models.IntegerField(verbose_name='NbGames')),
                ('kda', models.FloatField(verbose_name='KDA')),
            ],
        ),
    ]
