# Generated by Django 4.2.11 on 2024-05-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0010_championpool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championpool',
            name='patch',
        ),
    ]
