# Generated by Django 4.2.11 on 2024-05-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0011_remove_championpool_patch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpickorder',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='draftplayerpick',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
