# Generated by Django 5.0.6 on 2024-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draft', '0012_alter_draftpickorder_date_alter_draftplayerpick_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionBanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.CharField(max_length=240, verbose_name='ChampionName')),
                ('patch', models.CharField(max_length=240, verbose_name='Patch')),
                ('tournament', models.CharField(max_length=240, verbose_name='Tournament')),
                ('side', models.CharField(max_length=240, verbose_name='Side')),
                ('globalBanRate', models.FloatField(verbose_name='GlobalBanRate')),
                ('banRate1Rota', models.FloatField(verbose_name='BanRate1Rota')),
                ('banRate2Rota', models.FloatField(verbose_name='BanRate2Rota')),
            ],
        ),
    ]
